apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  restartPolicy: Always
  containers:
  - name: storage-pod
    image: busybox
    command: ["/bin/sh", "-c", "sleep 30s"]
    volumeMounts:
      - name: vol
        mountPath: /data 
        mountPropagation: "HostToContainer"
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: hpvc