apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: carol-pods
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io