apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-01
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1 
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: default
